import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>BRACKET</title>
        <meta name="description" content="Generated by Daechuyaza" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </div>
  );
};

export default Home;
